parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: true

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  - test-build-1

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scipp-developer.yml'
    deploy: true
    conda_label: 'test'
    publish_docs: false
